### ISSUE TITLE
Can't post pictures from web (with a URI)

### ISSUE THREAD

**Issue by mogita** [themattharris/tmhOAuth#49] opened 2012-04-27 02:53 UTC
Thanks Matt, this library works just fine.

There I met an issue though. When trying to post an image file from the web using its URI, and put the URI into one of the elements for the request array parameter, like this:

```
$img = 'http://distilleryimage11.s3.amazonaws.com/d8f7dc28825b11e180d51231380fcd7e_7.jpg';

$code = $tmhOAuth->request('POST', 'https://upload.twitter.com/1/statuses/update_with_media.json',
  array(
    'media[]'  => "@$img",
    'status'   => "Test uploading.".time() // Don't give up..
  ),
  true, // use auth
  true  // multipart
);
```

And var_dump() the tmhOAuth's response, there it says:

```
["error"]=>
  string(102) "couldn't open file "http://distilleryimage11.s3.amazonaws.com/d8f7dc28825b11e180d51231380fcd7e_7.jpg"
"
["errno"]=>
  int(26)
```

and of course the picture wasn't posted to my twitter timeline. But with a local image file it works fine, like "./picture.jpg".
Now what I'm doing is file_put_contents() the image from web to my local storage, then post the stored file. 
Please have a look at this. Thank you!

**Comment by mente** [comment] 2012-04-30 12:02
Try using media without `@`. Probably curl tries to find file locally and fails to do it

**Comment by mogita** [comment] 2012-04-30 12:37
@mente I removed the @ sign and got "(403) Error creating status" response. Tried several different image sources, the error messages were the same. And thank you anyway =)

**Comment by mente** [comment] 2012-04-30 14:07
lib won't make any magic, it's a simple wrapper over rest call. [Check documentation](https://dev.twitter.com/docs/api/1/post/statuses/update_with_media). Looks like it doesn't support external images uploading. You will have to upload it first.

**Comment by mogita** [comment] 2012-04-30 14:25
@mente Thanks! It seems I have to download the image file first in order to upload.

**Comment by themattharris** [comment] 2012-05-06 04:33
@mente thanks for helping with this one - appreciate you stepping in.

@mogita a little bit more background: the issue is that cURL itself, which tmhOAuth uses, doesn't support POSTing a file using a URL. instead the file being POSTed must be local to the script performing the upload - which means uploading to your server, and then to POSTing to Twitter.  I have an example where I do this in https://github.com/themattharris/tmhOAuth/blob/master/examples/images.php.

hope that helps.

**Comment by themattharris** [comment] 2012-05-22 05:24
gonna close this issue as it the answers above explain that you need to post the image from the host running the code, rather than posting via a URL.

**Closed as completed by themattharris** 2012-05-22 05:24 UTC
Labels: support

**Comment by innova** [comment] 2013-05-04 06:01
Hi  mogita
No need to download image from s3 bucket to your server. Following code works fine for me. I just create stream from amazon s3 image url then set it as post field.

```
    $image = file_get_contents('http://distilleryimage11.s3.amazonaws.com/d8f7dc28825b11e180d51231380fcd7e_7.jpg');
    $code = $tmhOAuth->request('POST', 'https://upload.twitter.com/1/statuses/update_with_media.json',
    array(
    'media[]'  => $image,
    'status'   => "Test uploading.".time() // Don't give up..
    ),
    true, // use auth
    true  // multipart
    );
```

Thanks
