### ISSUE TITLE
411 error after some months

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#95] opened 2012-10-28 04:17 UTC
For 2-3 months I use same oauth process.

`$code = $tmhOAuth->request('POST', $tmhOAuth->url('oauth/access_token', ''),
                array( 'oauth_verifier' => $_REQUEST['oauth_verifier']    ));`

although it worked very well for that months, since 30 hours I get status code 411.
I didn't change anything in my codes. What would be the problem. Can you give a tip?

**Comment by oosswwaalldd** [comment] 2012-10-28 04:18
Check out the issue #94

**Comment by themattharris** [comment] 2012-10-28 05:37
@trante as @oosswwaalldd mentions - this is a duplicate of issue #94 - check that one out and you'll see i released a new version today to handle that problem. 

let me know on issue #94 if 0.7.1 doesn't work for you

**Closed as completed by themattharris** 2012-10-28 05:37 UTC
Labels: bug

**Comment by trante** [comment] 2012-10-28 13:41
Thank you for quick reply that fixed issue. Sorry for duplicate.
