### ISSUE TITLE
Support for Composer

### ISSUE THREAD

**Issue by mishak87** [themattharris/tmhOAuth#54] opened 2012-05-24 11:28 UTC
Hi, 
I would appreciate if you could support http://packagist.org/ repository system for php. I is just one json file. Thanks

**Comment by christianchristensen** [comment] 2012-05-29 02:38
(Note: there may be a better place to put this...) I was looking at this project, but was a bit hampered by the lack of composer (although, I believe with a little more research could probably just use the git repo in a composer config...); however, I decided to move forward with the original PEAR libraries for OAuth (https://gist.github.com/2495726), this might serve as an example for how to depend on the libs if necessary.

**Comment by themattharris** [comment] 2012-09-04 04:17
Duplicate of #39

**Closed as completed by themattharris** 2012-09-04 04:17 UTC
Labels: feature
