### ISSUE TITLE
Warnings from IDE

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#51] opened 2012-05-05 17:06 UTC
I use phpStorm IDE.
And it gives many warnings in my code. Most of them because of **response** and **request**
Can you recommend me a way to discard tmhOAuth based warnings?

`$code=$tmhOAuth->request('GET', $tmhOAuth->url('1/account/totals') );`
Warning: 'void' method 'request' result used

`$responseData = json_decode($tmhOAuth->response['response'],true);`
Field 'response' not found in class tmhOAuth

**Comment by themattharris** [comment] 2012-05-06 04:06
this is a duplicate of issue#47 so i'm going to close it

**Closed as completed by themattharris** 2012-05-06 04:06 UTC
Labels: bug

**Comment by trante** [comment] 2012-05-06 09:34
I'm sorry i missed.
