### ISSUE TITLE
Image background Issue

### ISSUE THREAD

**Issue by Dementetech** [themattharris/tmhOAuth#2] opened 2010-10-11 19:46 UTC
Hi,

I'm traing to upload a background, im using the example 'images.php', but the system always return error 403 with this message:

" There was a problem with your background image. Probably too big."

I upload images of small sizes 15kb but either work.

could someone explain me what im doing wrong? or if curl need some extra configuration to work.

**Comment by Dementetech** [comment] 2010-10-12 19:08
I found a solultion, but is estranger.   in the example images.php have this line

 $params = array(
    'image' => "@{$_FILES['image']['tmp_name']};type={$_FILES['image']['type']};filename={$_FILES['image']['name']}",
  );

but i foun in other library that put and "@" before the parameter name, like:

 $params = array(
    '@image' => "@{$_FILES['image']['tmp_name']};type={$_FILES['image']['type']};filename={$_FILES['image']['name']}",
  );

and work for me, i dont know if is a curl bug or a different curl version. 

from my phpinfo..
cURL support    enabled
cURL Information    libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5

**Comment by themattharris** [comment] 2010-10-15 01:01
It could well be an issue with the version of CURL you have running. Mine is version 7.20.0. I'll look into this further but i'm glad to hear to you got it working.

**Comment by themattharris** [comment] 2011-03-03 23:25
Closing this as I haven't had other reports of needing this. I know PHP 5.2 changed some things with how this was handled so i'm curious if that was the cause. If anybody finds out more information add a comment and i'll try and add a workaround.

**Closed as completed by themattharris** 2011-03-03 23:25 UTC
Labels: support
