### ISSUE TITLE
Call to undefined function curl_init()

### ISSUE THREAD

**Issue by myronjhicks** [themattharris/tmhOAuth#63] opened 2012-07-24 16:02 UTC
Fatal error: Call to undefined function curl_init() in C:\xampp\htdocs\TwitterApp\tmhoauth\tmhOAuth.php on line 567

The error I get when trying to recreate your simple tweet example, would you have any input on this?

**Comment by themattharris** [comment] 2012-07-24 17:18
it sounds like your PHP installation doesn't include support for libcurl. if you run:

```
php -i | grep curl -i
```

do you get anything displayed? if not you need to talk to your hosting provide about having libcurl support added to your install.

**Comment by myronjhicks** [comment] 2012-07-24 18:24
Thanks I found the issue, but before we close the issue, I've taken a look at response codes, but the response code I am getting is 0. Do you have any input?

**Comment by themattharris** [comment] 2012-07-24 19:04
if you look at the output of $tmhOAuth->response['error'] it will include some information about the error. the most common cause of the 0 return is the SSL connection couldn't be established. this is normally because the .pem file included in tmhOAuth isn't included in the root of your project.

**Comment by myronjhicks** [comment] 2012-07-24 19:31
That didnt seem to do the trick, if you have any other input I'd appreciate it if not thank you for the responses.

**Comment by themattharris** [comment] 2012-07-24 19:45
if you can share the result of var_dump($tmhOAuth->response) i can take a look and see what's happening. remember to remove any secrets or passwords which may exist in the object before pasting.

**Comment by myronjhicks** [comment] 2012-07-24 20:28
I'm not even sure I understand how to call that or where the output would be. Although I have some coding knowledge I dont know a lot about it. I'm working in the IDE Netbeans. I can tell you that when I call for the response I get nothing in return as output to the web browser.

**Comment by themattharris** [comment] 2012-07-24 20:29
add this to the end of the script:

```
var_dump($tmhOAuth->response);
```

**Comment by myronjhicks** [comment] 2012-07-24 20:45
Thanks the response is: 

array (size=5)
  'code' => int 0
  'response' => boolean false
  'info' => 
    array (size=26)
      'url' => string 'https://api.twitter.com/1/statuses/update.json' (length=46)
      'content_type' => null
      'http_code' => int 0
      'header_size' => int 0
      'request_size' => int 0
      'filetime' => int -1
      'ssl_verify_result' => int 0
      'redirect_count' => int 0
      'total_time' => float 4.072
      'namelookup_time' => float 0.063
      'connect_time' => float 0
      'pretransfer_time' => float 0
      'size_upload' => float 0
      'size_download' => float 0
      'speed_download' => float 0
      'speed_upload' => float 0
      'download_content_length' => float -1
      'upload_content_length' => float -1
      'starttransfer_time' => float 0
      'redirect_time' => float 0
      'certinfo' => 
        array (size=0)
          empty
      'primary_ip' => string '19.'(length=13)
      'primary_port' => int 443
      'local_ip' => string '' (length=0)
      'local_port' => int 0
      'redirect_url' => string '' (length=0)
  'error' => string 'couldn't connect to host' (length=24)
  'errno' => int 7

**Comment by themattharris** [comment] 2012-07-24 22:36
ok, this is suggestion your server is unable to connect over SSL.
as an experiment, try doing this when you create the $tmhOAuth object.

```
$tmhOAuth = new tmhOAuth(array(
  'consumer_key'    => 'YOUR_CONSUMER_KEY',
  'consumer_secret' => 'YOUR_CONSUMER_SECRET',
  'user_token'      => 'A_USER_TOKEN',
  'user_secret'     => 'A_USER_SECRET',
  'use_ssl'         => false,
));
```

i don't recommend keeping it that way, but it will test whether the problem is with your SSL setup or not.

**Comment by myronjhicks** [comment] 2012-07-25 17:28
The problem that I was having came from issues using xammp and locoalhost Im guessing as I was connected through my company's VPN. Once I got home I was able to run it without any problems. One more question, I'm trying to go through your steps in getting a user's tokens. I came across other issues on here which you pointed out that they should leave the user token fields blank when calling the object. After doing so I'm still not able to authorize access, could this be because I'm using my twitter name and password which has already been given access through the developers side of twitter?

**Comment by themattharris** [comment] 2012-09-04 03:45
sorry for the delay in responding to your last comment - super happy you were able to track down the connection issue though.

for your other question: which auth example are you using? it sounds like you are entering a username and password in the script somewhere - perhaps the xAuth example? for xAuth - you must have Twitter's permission before xAuth will work.

if you know the access token/secret for a user on your app then you do not need to go through the auth process again. instead, you can just set the user_token and user_secret in the initialization array for the tmhOAuth class and then use the API (see tweet.php for example).

if you are using the other auth (auth.php) example though, yes, you must ensure the user_token and user_secret and not specified (because you don't know then yet right?). then, when you go through the flow, you should find yourself redirected to the Twitter website. from there you would login, authorise the app, and then Twitter would meta-refresh your browser to the callback URL. the auth.php example would then complete the auth flow and store the now returned user_token and user_secret in the $SESSION object.

last thing, if you have already authorised the application Twitter will, as long as you don't force the OAuth access type, return the existing token and secret for that user.

hope that helps.

**Comment by LeagueRivals** [comment] 2012-09-09 20:05
I have the same Fatal Error as the original post - Call to undefined function curl_init() in C:.....tmhOAuth.php on line 581? I'm currently running it through a testing server on Dreamweaver. Any help would be appreciated. Ta

**Comment by themattharris** [comment] 2012-09-10 21:27
hey tatters1979,
the error `undefined function curl_init()` suggests your install doesn't have support for curl compiled.

when you look at your PHP info do you see curl listed? you can do this using a script like this:

```
<?php
    phpinfo();
```

also, can you tell me if you are running this on a mac/linux/windows machine? (if you don't have curl installed the solution varies between platforms).

**Comment by neave** [comment] 2012-09-11 09:18
I had this same problem on Mac OS X. Curl wasn't installed with my PHP set up. It's simple to fix if you're using MacPorts:

`sudo port install php5-curl`

Then restart your PHP server or web server.

**Comment by LeagueRivals** [comment] 2012-09-11 18:06
Thanks for the quick response Matt/neave, I found the curl file in the C:\xampp\php files. I added it to my php files but I seem to have a new error?

Fatal error: require() [function.require]: Failed opening required 'C:/xampp/htdocs/check_php/admin/tmhUtilities.php' (include_path='.:/usr/services/vux/lib/php') in /data/17/2/90/131/2742131/user/3013853/htdocs/index.php on line 40

I'm pretty new to php, do I need a mysql database for this image-tweet.php?

**Comment by themattharris** [comment] 2012-09-12 15:18
neave, thanks for helping tatters1979 out.
tatters1979 - glad you got the curl functionality working on your machine. 
for the latest issue you are reporting PHP is trying to tell you it can't find the file tmhUtilities.php in path `C:/xampp/htdocs/check_php/admin/`. 

try putting `tmhUtilities.php`, and `cacert.pem`, in the same location as the `tmhOAuth.php` script, and `require`ing `tmhUtilities.php` the same way `tmhOAuth.php` is required in your script.

tmhOAuth itself doesn't have database support built in - but, if you wish, you can code your own database handlers into it for persistent storage of user tokens and secrets.

**Comment by LeagueRivals** [comment] 2012-09-12 22:04
Massive thanks Matt, the file path on my hosting is a weird one (hosting with Network Solutions). Anyway I sorted it out and the picture posted perfectly. Awesome script, cheers mate.

**Comment by themattharris** [comment] 2012-09-12 23:47
great news, glad you worked it out and got things going. i'll close this out.

**Closed as completed by themattharris** 2012-09-12 23:47 UTC
Labels: support
