### ISSUE TITLE
Can't use statuses/update_with_media

### ISSUE THREAD

**Issue by thatg33k** [themattharris/tmhOAuth#153] opened 2013-08-19 13:15 UTC
Hello sir,

i think there's a problem somewhere that i can't find. I've been using your class for a while now, and it's always been working fine. Last week, i realized that my posts weren't on twitter, so i started debugging and i realized i always receive : 

```
[error] => Operation timed out after 30000 milliseconds with 0 bytes received
[errno] => 28
```

This seems to be an error sent back from cURL after it reached it's timeout value in the settings. I've tried setting that value higher, and i obtain the same result.

I'm wondering if you had any idea what could block cURL for that long, the headers looks fine and here my code 

require_once('tmhOAuth.php');

function tweet($message,$imagepath){
        $tmhOAuth = new tmhOAuth();

```
    $message = sprintf("\0%s", $message);

    $code = $tmhOAuth->user_request(array(
    'method' => 'POST',
    'url' => $tmhOAuth->url('1.1/statuses/update_with_media'),
    'params' => array(
        'media[]' => "@{$imagepath}",
        'status' => $message
    ),
'multipart' => true,
    ));

print_r($tmhOAuth->response);
```

}

tweet("test sadadasa","./test.jpg");

Thanks,

**Comment by themattharris** [comment] 2013-08-19 18:06
have you tried pinging, tracerouting and just plain curling to api.twitter.com? a timeout that high suggests there's a networking issue preventing your host reaching api.twitter.com.

**Comment by thatg33k** [comment] 2013-08-19 21:04
I did some tests, using some other classes, and i get the same issue ... disregard this is either a bug in Twitter API or something weird with cURL ... i'm posting without media for now ... cause it's working fine without any media!

Thanks,

**Comment by thatg33k** [comment] 2013-08-20 16:00
Hi Matt,

can you verify your update_with_media feature? I spoke with other twitter PHP guys, and they tested theirs and it's no longer working...

https://dev.twitter.com/discussions/20720

I just want to make sure it's working on your side or not!

Thanks,

**Comment by themattharris** [comment] 2013-08-20 16:25
using tmhOAuth 0.8.3 (0.8.2 also works) and the example photo_tweet.php script here's what i get

```
php photo_tweet.php 
Request Settings
================
params                   
     media[]                  @/workspace/tmhOAuthExamples/cli/guitar.jpg;type=image/jpeg;filename=guitar.jpg
     status                   Picture time
headers                  
     Authorization            OAuth oauth_consumer_key="<removed>", oauth_nonce="989ce64cf741682edb799d328fcd6c08", oauth_signature="<removed>", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1377015570", oauth_token="<removed>", oauth_version="1.0"
with_user                1
multipart                1
method                   POST
without_bearer           
url                      https://api.twitter.com/1.1/statuses/update_with_media.json
oauth1_params            
     oauth_consumer_key       <removed>
     oauth_nonce              989ce64cf741682edb799d328fcd6c08
     oauth_signature          <removed>
     oauth_signature_method   HMAC-SHA1
     oauth_timestamp          1377015570
     oauth_token              <removed>
     oauth_version            1.0
prepared_params          
     media[]                  @/workspace/tmhOAuthExamples/cli/guitar.jpg;type=image/jpeg;filename=guitar.jpg
     status                   Picture time
basestring_params        oauth_consumer_key=<removed>&oauth_nonce=989ce64cf741682edb799d328fcd6c08&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1377015570&oauth_token=<removed>&oauth_version=1.0
postfields               
     media[]                  @/workspace/tmhOAuthExamples/cli/guitar.jpg;type=image/jpeg;filename=guitar.jpg
     status                   Picture time
basestring               <removed>
signing_key              <removed>

Request Headers
===============
POST /1.1/statuses/update_with_media.json HTTP/1.1
User-Agent               tmhOAuth 0.8.3 Examples 0.1
Host                     api.twitter.com
Accept                   */*
Accept-Encoding          deflate, gzip
Authorization            OAuth oauth_consumer_key="<removed>", oauth_nonce="989ce64cf741682edb799d328fcd6c08", oauth_signature="<removed>", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1377015570", oauth_token="<removed>", oauth_version="1.0"
Content-Length           159430
Expect                   100-continue
Content-Type             multipart/form-data; boundary=----------------------------04c467686ba6


Request Data
============
url                      https://api.twitter.com/1.1/statuses/update_with_media.json
content_type             application/json;charset=utf-8
http_code                200
header_size              800
request_size             611
filetime                 -1
ssl_verify_result        0
redirect_count           0
total_time               1.139835
namelookup_time          0.000871
connect_time             0.007692
pretransfer_time         0.087931
size_upload              159430
size_download            1033
speed_download           906
speed_upload             139871
download_content_length  1033
upload_content_length    159430
starttransfer_time       0.095007
redirect_time            0
certinfo                 
primary_ip               <removed>
primary_port             443
local_ip                 <removed>
local_port               50456
redirect_url             

Response Headers
================
HTTP/1.1 100 Continue    

     0                        
     1                        
HTTP/1.1 200 OK          
cache-control            no-cache, no-store, must-revalidate, pre-check=0, post-check=0
content-encoding         gzip
content-length           1033
content-type             application/json;charset=utf-8
date                     Tue, 20 Aug 2013 16:19:31 GMT
expires                  Tue, 31 Mar 1981 05:00:00 GMT
last-modified            Tue, 20 Aug 2013 16:19:31 GMT
pragma                   no-cache
server                   tfe
set-cookie               
     0                        lang=en
     1                        <removed>
status                   200 OK
strict-transport-securitymax-age=631138519
x-access-level           read-write-directmessages
x-frame-options          SAMEORIGIN
x-mediaratelimit-class   photos
x-mediaratelimit-limit   100
x-mediaratelimit-remaining96
x-mediaratelimit-reset   1377041913
x-transaction            d5c7e26d8e3fe194

Response Body (As an Object)
============================
array(23) {
  ["created_at"]=>
  string(30) "Tue Aug 20 16:19:31 +0000 2013"
  ["id"]=>
  int(369856231357571072)
  ["id_str"]=>
  string(18) "369856231357571072"
  ["text"]=>
  string(35) "Picture time http://t.co/NRQXlfAmln"
  ["source"]=>
  string(84) "<removed>"
  ["truncated"]=>
  bool(false)
  ["in_reply_to_status_id"]=>
  NULL
  ["in_reply_to_status_id_str"]=>
  NULL
  ["in_reply_to_user_id"]=>
  NULL
  ["in_reply_to_user_id_str"]=>
  NULL
  ["in_reply_to_screen_name"]=>
  NULL
  ["user"]=>
  array(38) {
    ["id"]=>
    int(19345946)
    ["id_str"]=>
    string(8) "19345946"
    ["name"]=>
    string(9) "mattytest"
    ["screen_name"]=>
    string(9) "mattytest"
    ["location"]=>
    string(0) ""
    ["description"]=>
    string(37) "Something is afoot, quick fast foward"
    ["url"]=>
    NULL
    ["entities"]=>
    array(1) {
      ["description"]=>
      array(1) {
        ["urls"]=>
        array(0) {
        }
      }
    }
    ["protected"]=>
    bool(true)
    ["followers_count"]=>
    int(3)
    ["friends_count"]=>
    int(7)
    ["listed_count"]=>
    int(0)
    ["created_at"]=>
    string(30) "Thu Jan 22 16:27:50 +0000 2009"
    ["favourites_count"]=>
    int(1)
    ["utc_offset"]=>
    int(-25200)
    ["time_zone"]=>
    string(7) "Tijuana"
    ["geo_enabled"]=>
    bool(true)
    ["verified"]=>
    bool(false)
    ["statuses_count"]=>
    int(336)
    ["lang"]=>
    string(2) "en"
    ["contributors_enabled"]=>
    bool(false)
    ["is_translator"]=>
    bool(false)
    ["profile_background_color"]=>
    string(6) "131516"
    ["profile_background_image_url"]=>
    string(48) "http://a0.twimg.com/images/themes/theme14/bg.gif"
    ["profile_background_image_url_https"]=>
    string(50) "https://si0.twimg.com/images/themes/theme14/bg.gif"
    ["profile_background_tile"]=>
    bool(true)
    ["profile_image_url"]=>
    string(68) "http://a0.twimg.com/profile_images/1164269095/matt_orange_normal.jpg"
    ["profile_image_url_https"]=>
    string(70) "https://si0.twimg.com/profile_images/1164269095/matt_orange_normal.jpg"
    ["profile_link_color"]=>
    string(6) "009999"
    ["profile_sidebar_border_color"]=>
    string(6) "EEEEEE"
    ["profile_sidebar_fill_color"]=>
    string(6) "EFEFEF"
    ["profile_text_color"]=>
    string(6) "333333"
    ["profile_use_background_image"]=>
    bool(true)
    ["default_profile"]=>
    bool(false)
    ["default_profile_image"]=>
    bool(false)
    ["following"]=>
    bool(false)
    ["follow_request_sent"]=>
    bool(false)
    ["notifications"]=>
    bool(false)
  }
  ["geo"]=>
  NULL
  ["coordinates"]=>
  NULL
  ["place"]=>
  NULL
  ["contributors"]=>
  NULL
  ["retweet_count"]=>
  int(0)
  ["favorite_count"]=>
  int(0)
  ["entities"]=>
  array(5) {
    ["hashtags"]=>
    array(0) {
    }
    ["symbols"]=>
    array(0) {
    }
    ["urls"]=>
    array(0) {
    }
    ["user_mentions"]=>
    array(0) {
    }
    ["media"]=>
    array(1) {
      [0]=>
      array(10) {
        ["id"]=>
        int(369856231173021696)
        ["id_str"]=>
        string(18) "369856231173021696"
        ["indices"]=>
        array(2) {
          [0]=>
          int(13)
          [1]=>
          int(35)
        }
        ["media_url"]=>
        string(46) "http://pbs.twimg.com/media/BSH-SF0IYAAK-uW.jpg"
        ["media_url_https"]=>
        string(47) "https://pbs.twimg.com/media/BSH-SF0IYAAK-uW.jpg"
        ["url"]=>
        string(22) "http://t.co/NRQXlfAmln"
        ["display_url"]=>
        string(26) "pic.twitter.com/NRQXlfAmln"
        ["expanded_url"]=>
        string(62) "http://twitter.com/mattytest/status/369856231357571072/photo/1"
        ["type"]=>
        string(5) "photo"
        ["sizes"]=>
        array(4) {
          ["thumb"]=>
          array(3) {
            ["w"]=>
            int(150)
            ["h"]=>
            int(150)
            ["resize"]=>
            string(4) "crop"
          }
          ["small"]=>
          array(3) {
            ["w"]=>
            int(340)
            ["h"]=>
            int(253)
            ["resize"]=>
            string(3) "fit"
          }
          ["large"]=>
          array(3) {
            ["w"]=>
            int(1000)
            ["h"]=>
            int(747)
            ["resize"]=>
            string(3) "fit"
          }
          ["medium"]=>
          array(3) {
            ["w"]=>
            int(599)
            ["h"]=>
            int(448)
            ["resize"]=>
            string(3) "fit"
          }
        }
      }
    }
  }
  ["favorited"]=>
  bool(false)
  ["retweeted"]=>
  bool(false)
  ["possibly_sensitive"]=>
  bool(false)
  ["lang"]=>
  string(2) "en"
}

Raw response
============

HTTP/1.1 100 Continue

HTTP/1.1 200 OK
cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
content-encoding: gzip
content-length: 1033
content-type: application/json;charset=utf-8
date: Tue, 20 Aug 2013 16:19:31 GMT
expires: Tue, 31 Mar 1981 05:00:00 GMT
last-modified: Tue, 20 Aug 2013 16:19:31 GMT
pragma: no-cache
server: tfe
set-cookie: lang=en
set-cookie: guest_id=<removed>
status: 200 OK
strict-transport-security: max-age=631138519
x-access-level: read-write-directmessages
x-frame-options: SAMEORIGIN
x-mediaratelimit-class: photos
x-mediaratelimit-limit: 100
x-mediaratelimit-remaining: 96
x-mediaratelimit-reset: 1377041913
x-transaction: d5c7e26d8e3fe194

{"created_at":"Tue Aug 20 16:19:31 +0000 2013","id":369856231357571072,"id_str":"369856231357571072","text":"Picture time http:\/\/t.co\/NRQXlfAmln","source":"<removed>","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":19345946,"id_str":"19345946","name":"mattytest","screen_name":"mattytest","location":"","description":"Something is afoot, quick fast foward","url":null,"entities":{"description":{"urls":[]}},"protected":true,"followers_count":3,"friends_count":7,"listed_count":0,"created_at":"Thu Jan 22 16:27:50 +0000 2009","favourites_count":1,"utc_offset":-25200,"time_zone":"Tijuana","geo_enabled":true,"verified":false,"statuses_count":336,"lang":"en","contributors_enabled":false,"is_translator":false,"profile_background_color":"131516","profile_background_image_url":"http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif","profile_background_image_url_https":"https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif","profile_background_tile":true,"profile_image_url":"http:\/\/a0.twimg.com\/profile_images\/1164269095\/matt_orange_normal.jpg","profile_image_url_https":"https:\/\/si0.twimg.com\/profile_images\/1164269095\/matt_orange_normal.jpg","profile_link_color":"009999","profile_sidebar_border_color":"EEEEEE","profile_sidebar_fill_color":"EFEFEF","profile_text_color":"333333","profile_use_background_image":true,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"symbols":[],"urls":[],"user_mentions":[],"media":[{"id":369856231173021696,"id_str":"369856231173021696","indices":[13,35],"media_url":"http:\/\/pbs.twimg.com\/media\/BSH-SF0IYAAK-uW.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/BSH-SF0IYAAK-uW.jpg","url":"http:\/\/t.co\/NRQXlfAmln","display_url":"pic.twitter.com\/NRQXlfAmln","expanded_url":"http:\/\/twitter.com\/mattytest\/status\/369856231357571072\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"small":{"w":340,"h":253,"resize":"fit"},"large":{"w":1000,"h":747,"resize":"fit"},"medium":{"w":599,"h":448,"resize":"fit"}}}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"}
```

**Comment by themattharris** [comment] 2013-08-20 16:27
i just noticed the \0 in your status. can you try removing that.
\0 is a null terminator and i strongly recommend against using it. v0.8.3 handles @reply handling by putting a space at the beginning of the string

**Comment by thatg33k** [comment] 2013-08-20 16:39
I tried removing the \0 ... same results! I'll start from scratch given your examples and i'll see from there! Weird stuff tho ...

thanks for testing

**Comment by themattharris** [comment] 2013-08-20 16:50
if you can send me your actual code and image you are trying to post i can try digging in a little deeper. remove your keys though :)

**Comment by thatg33k** [comment] 2013-08-20 17:10
Well i just redownloaded your scripts and test using your code for photo_tweet.php and here the result : 

# Request Settings

params  
     media[]                  @/path/test/test.jpg;type=image/jpeg;filename=test.jpg
     status                   Picture time
headers  
     Authorization            OAuth oauth_consumer_key="-", oauth_nonce="-", oauth_signature="-", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1377018400", oauth_token="-", oauth_version="1.0"
with_user                1
multipart                1
method                   POST
without_bearer  
url                      https://api.twitter.com/1.1/statuses/update_with_media.json
oauth1_params  
     oauth_consumer_key       -
     oauth_nonce             -
     oauth_signature          -
     oauth_signature_method   HMAC-SHA1
     oauth_timestamp          1377018400
     oauth_token             -
     oauth_version            1.0
prepared_params  
     media[]                  @/path/test/test.jpg;type=image/jpeg;filename=test.jpg
     status                   Picture time
basestring_params        oauth_consumer_key=-&oauth_nonce=-&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1377018400&oauth_token=-&oauth_version=1.0
postfields  
     media[]                  @/path/test/test.jpg;type=image/jpeg;filename=test.jpg
     status                   Picture time
basestring               POST&https%3A%2F%2Fapi.twitter.com%2F1.1%2Fstatuses%2Fupdate_with_media.json&oauth_consumer_key-oauth_nonce-oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1377018400%26oauth_token-26oauth_version%3D1.0
signing_key-

# Request Headers

POST /1.1/statuses/update_with_media.json HTTP/1.1
User-Agent               tmhOAuth 0.8.3 Examples 0.1
Host                     api.twitter.com
Accept                   _/_
Accept-Encoding          deflate, gzip
Authorization            OAuth oauth_consumer_key="-", oauth_nonce="-", oauth_signature="-", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1377018400", oauth_token="-", oauth_version="1.0"
Content-Length           138193
Expect                   100-continue
Content-Type             multipart/form-data; boundary=----------------------------010ff93540d4

Request Data
namelookup_time          0.000128
connect_time             0.043726
pretransfer_time         0.165452
size_upload              32909
size_download            0
speed_download           0
speed_upload             3194
download_content_length  -1
upload_content_length    138193
starttransfer_time       0.209432
redirect_time            0
certinfo                 

# Response Headers

HTTP/1.1 100 Continue    

# Response Body (As an Object)

NULL

# Raw response

HTTP/1.1 100 Continue

It's not working ... even with your example ... could it be related to curl version? or PHP version?

curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

PHP 5.3.3 (cli) (built: Jul 12 2013 20:35:47) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

**Comment by thatg33k** [comment] 2013-08-20 17:18
content_type             application/json;charset=utf-8 ... is it normal that mine is empty?

**Comment by thatg33k** [comment] 2013-08-22 14:00
Hi Matt,

can you take a look at this : https://dev.twitter.com/discussions/20720#comment-47790

A lot of users are using your library and reporting issues with update_with_media, i think it's worth a shot that you read that thread and see if anything makes sense to you.

thanks

**Comment by themattharris** [comment] 2013-08-22 15:28
thanks for signposting.
i see a number of different issues with different libraries being reported so i think theres some conflation going on.

i agree something is up though.

as i'm not able to reproduce this yet (i've tried different apps, machines, users and php versions) i need to trouble you for some more info.

can you tell me the ip you're making your requests from (working and non-working) and also what ip 'ping api.twitter.com' uses. i know they have a few so i want to make sure i'm hitting the same one as you.

also, to get as close as i can to your requests is the image a jpeg, png? and what filesize is it.

thanks

**Comment by thatg33k** [comment] 2013-08-22 16:00
Hi Matt,

when i saw the problem, i created a hosts entry in my /etc/hosts so i can always use the same twitter server, so i currently use : 199.16.156.104 api.twitter.com

api.twitter.com is a round-robin DNS, so i guess we must not hit the same server quite often, but if you modify your hosts file you can force it to go to the same as me.

my ip is : 198.245.51.14 and i don't have any working IP right now, this is my only server

This is the image i use : http://i.imgur.com/b262bmL.jpg (i use a local copy of that image, i just uploaded it to imgur so you can download it and test with it)

I think that's about it ... do you have any special config in your tmhoauthexample as of headers configuration, for content-type and stuff like that?

**Comment by themattharris** [comment] 2013-08-23 03:19
thanks for the information and the file you are testing. still getting ok results so i'm attempting to compile the versions of php and libcurl you are using.

there's no chance you could use wireshark and record what's happening when you try and make requests is there?

**Comment by thatg33k** [comment] 2013-08-23 04:08
Hi Matt,

here the tcp stream ... i removed my keys of course, and i did it without SSL to grab all the info.

http://pastebin.com/HtXX6ttD

And i also took a screenshot of wireshark results, there's a lot of TCP retransmission, and a weird error at the end

http://i.imgur.com/el0nLhB.png

"20 13.037826   198.245.51.14   199.16.156.104  HTTP    1514    [TCP Retransmission] Continuation or non-HTTP traffic (JPEG JFIF image)"

If you can do it on your side, and see if we can correlate the results

**Comment by themattharris** [comment] 2013-08-23 04:14
ok just compiled php 5.3.3 with libcurl 7.19.7 - still everything works.
so i've done a bit more background research and here's what i'm interpreting from the curl stats you published.

here are the stats for my connection to the 199.16.156.104 address:

```
url                      https://api.twitter.com/1.1/statuses/update_with_media.json
content_type             application/json;charset=utf-8
http_code                200
header_size              800
request_size             613
filetime                 -1
ssl_verify_result        0
redirect_count           0
total_time               1.085961
namelookup_time          0.018935
connect_time             0.101875
pretransfer_time         0.313148
size_upload              138124
size_download            1043
speed_download           960
speed_upload             127190
download_content_length  1043
upload_content_length    138124
starttransfer_time       0.396972
redirect_time            0
```

of interest here are these values:

```
total_time               1.085961
size_upload              138124
speed_upload             127190
upload_content_length    138124
```

what those values tell me is that my connection uploaded size_upload bytes, or upload_content_length bytes at an average speed of speed_upload bytes per second.

now, if we take a look at your stats we see a very different story:

```
total_time               <this doesn't exist in yours due to the timeout>
size_upload              32909
speed_upload             3194
upload_content_length    138193
```

what this tells me is your connection provided an average speed of 3194 bytes per second. in the time it was connected it was able to upload 32909 bytes of 138193. now, if the average transfer speed is 3194 bytes per second , your 138193 bytes of content would take >40 seconds to complete -- which is longer than the 30 second timeout the connection allows.

whether this is you or not i don't know (i'll review your wireshark values in a minute) but it does suggest that this issue is something on the wire.

**Comment by thatg33k** [comment] 2013-08-23 04:31
I checked my interface and there's no dropped packets etc... i did a traceroute so here it is : 

 1  198.245.51.253  1.505 ms \* *
 2  198.27.73.15  1.149 ms  1.453 ms  1.461 ms
 3  198.27.73.6  156.507 ms  156.518 ms *
 4  \* \* *
 5  206.223.119.171  17.949 ms  17.964 ms  17.953 ms
 6  199.16.159.34  46.090 ms  46.219 ms  46.195 ms
 7  199.16.159.73  43.077 ms  43.421 ms  43.168 ms
 8  199.16.156.104  43.170 ms  45.964 ms  45.929 ms

Using MTR ... i get a lot of % dropped at api.twitter.com

**Comment by thatg33k** [comment] 2013-08-23 13:39
Hi Matt, i was debugging again this morning and after some tests failed ... my tests went through very quickly. I did some upload, and they all went through ...

I retested my website integration and it was working too ... i guess this was really on twitter end!

I'm waiting for an answer on the developper discussion and will report back

Thanks for all the hard work

EDIT: Finally it went back to not working after 5 minutes ... Twitter stop messing with us :)

**Comment by themattharris** [comment] 2013-08-23 14:53
what time range was it working during, this might help focus on whats happening. for something to work and then not work within that short space of time really does suggest a network event somewhere along the line.

i think we can rule out tmhOAuth as the cause though.

**Comment by themattharris** [comment] 2013-08-28 03:57
have you seen any improvement or success in the last few days?

**Comment by thatg33k** [comment] 2013-08-28 13:08
Not really, i've seen people yesterday having success with it, but it's back to not working this morning. It's definitely not your code, so if you want to close this here, go ahead, or leave it open and i'll update as soon as Twitter get their fingers out of their nose and figure out what's happening.

**Comment by themattharris** [comment] 2013-08-28 17:22
yeah still, i'm keen to help you resolve this.
so, and i appreciate you doing these tests, can you do two thing for me?
1. let me know if a profile image can be uploaded successfully. (use a test account just incase)
2. email me (its on my github profile page)  the full wireshark capture for the failing media upload so i can dig into the packet messages?

**Comment by cwoodfield** [comment] 2013-09-02 18:00
Hi, I'm on Twitter's Network Eng team. Was wondering if you could do some extra diags on your side to help us try to pin this down...?

First off, from the capture you sent in (thank you very much for this!), it's apparent that your client has segmentation offload enabled, resulting in an inaccurate pcap (the pcap shows packets larger than the MTU that are broken up into MTU-sized frames by the driver). See http://rtoodtoo.net/2011/08/16/generic_segmentation_offload_and_wireshark/ for more info on segmentation offload.

To get an accurate capture, you'll need to disable those options using ethtool.

You can see which options are enabled by running (assuming eth0 is your network interface:

```
sudo ethtool -k eth0
```

You should see that one or both of the options "tcp-segmentation-offload" and "generic-segmentation-offload" will be turned on.

Then you can disable those options with:

```
sudo ethtool -K eth0 tso off gso off
```

Redo your packet capture, then run the following to re-enable (assuming both were on before):

```
sudo ethtool -K eth0 tso on gso on
```

Check your pcap and make sure there are no frames larger than 1500 bytes captured.

One more thing I'd like you to try - redo your previous mtr command with the "--psize 1500" option. Be interested to see if the output is any different from your prior test.

Thanks!

**Comment by thatg33k** [comment] 2013-09-02 20:01
Where do i send the pcap file? I won't add it here since it's not SSL traffic and my keys are inside the pcap file.

Just did the MTR test, and i get the same results
                                                                                                                                                                      Packets               Pings
 Host                                                                                                                                                               Loss%   Snt   Last   Avg  Best  Wrst StDev
1. 198.245.51.253 18.6%    60   69.3  34.0   1.0 465.2  79.5
2. 198.27.73.15 0.0%    60    1.4   1.5   1.2   2.7   0.4
3. 198.27.73.6  0.0%    59   18.8   6.3   2.2 175.3  23.2
4. 198.27.73.178 98.3%    59   18.2  18.2  18.2  18.2   0.0
5. ???
6. 199.16.159.34  0.0%    59   31.4  33.2  31.0  55.0   5.0
7. 199.16.159.73  0.0%    59   43.5  45.8  43.3  93.2   8.2
8. ???

**Comment by cwoodfield** [comment] 2013-09-02 20:12
You can email to me, see my profile page.

**Comment by thatg33k** [comment] 2013-09-03 13:54
After discussion with cwoodfield, the problem seems to be fixed. So i guess it was really a network issue, or something related.

Thanks for everyone, but i think this issue can be close now, as long as Twitter doesn't revert back the changes they made :+1:

**Comment by Maxwell2022** [comment] 2013-09-04 00:52
it seems to have been fixed by twitter: https://dev.twitter.com/discussions/20720?page=1#comment-48686

**Closed as completed** 2013-09-19 15:18 UTC
Labels: support

**Comment by ramachandra357** [comment] 2014-06-06 12:34
Hi Matt Harris,
I have used your class file (tmhOAuth.php) but I'm facing a problem while updating twitter background i.e if a user having his /her background image inbuilt theme(provided by twitter) my application unable to change it. Can you please mention how can I resolve this problem. 

Thanks in advance
