### ISSUE TITLE
401 Could not authenticate you error

### ISSUE THREAD

**Issue by trante** [themattharris/tmhOAuth#83] opened 2012-09-17 19:41 UTC
I can successfully use tmhOAuth for signined users. Everything is OK when I use users' access tokens. I can use their tokens for nearly every API request.

Then I tried to use my application's access tokens. I opened application page:
[http://i46.tinypic.com/1i1hk4.jpg](http://i46.tinypic.com/1i1hk4.jpg)

And copied "access token" and "access token secret" values to following code snippet. But I get "could not authenticate you" error. I'm sure that I copied tokens correctly. Should I take anything more into consideration?

```
$tmhOAuth = new tmhOAuth
    (array( 'consumer_key'    => YOUR_CONSUMER_KEY,
         'consumer_secret' => YOUR_CONSUMER_SECRET,
    'user_token'      => $atoken1,
        'user_secret'     => $atoken2, )
    );

$code=$tmhOAuth->request('GET',
     $tmhOAuth->url('1.1/account/rate_limit_status') );
```

**Comment by GhostToast** [comment] 2012-10-15 18:51
Try to recreate all your keys, this worked for me.

**Comment by themattharris** [comment] 2012-10-27 19:48
agreed, as @GhostToast states - your access token and secret reported on dev.twitter.com _may_ not be correct. recreating them using the console should fix this problem for you.

also, double check the consumer_key and secret, user token and secret from the page do match what's in your code. it's really easy to miss a character of the end or the beginning when copying and pasting.

closing this issue out though as it's not a bug with tmhOAuth.

**Closed as completed by themattharris** 2012-10-27 19:48 UTC
Labels: support
