### ISSUE TITLE
Twitter REST API v1.1 appears to require non-empty Content-Length on POST

### ISSUE THREAD

**Issue by ghost** [themattharris/tmhOAuth#93] opened 2012-10-26 22:43 UTC
A bit of an FYI:

I used to use tmhAOuth 0.14 and the Twitter API v1 without any issue and I could delete a status via

$tmhOAuth->request('POST', $tmhOAuth->url('1/statuses/destroy/'.$id));

when I upgraded to tmhOauth 0.70 and the new Twitter REST API v1.1 was released, this no longer works and was getting a '411 Content-Length Required' message. I have to provide a non-empty array to the post param attribute

$tmhOAuth->request('POST', $tmhOAuth->url('1.1/statuses/destroy/'.$id), array('dummy'=>'dummy'));

and it all works fine now.

**Comment by neave** [comment] 2012-10-27 08:48
Thanks @pavemen has this been filed at https://dev.twitter.com/issues anywhere do you know?

**Comment by themattharris** [comment] 2012-10-27 18:10
duplicate of #94, we'll track this under that ticket instead.

**Closed as completed by themattharris** 2012-10-27 18:10 UTC
Labels: bug

**Comment by rasa** [comment] 2012-11-02 20:18
Bug filed here: https://dev.twitter.com/issues/643
